### ISSUE TITLE
 Delete history of redirect links 

### ISSUE THREAD

**Issue by DeepChirp** [sblask-webextensions/webextension-skip-redirect#359]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)
I hope the extension can delete the history of redirected links, as this is unnecessary.   For example, if A is a link redirected to B, then both A and B will now be retained in the history. However, in reality, A is useless and it is best to be removed.

**Comment by sblask** [comment]
Won't do.
