### ISSUE TITLE
Skip checkpoint redirects

### ISSUE THREAD

**Issue by acjbrouwer** [sblask-webextensions/webextension-skip-redirect#364]
### New Issue Checklist (tick off like this: `[x]`)

- [ ] I checked existing issues (open and closed) for possible duplicates
- [ ] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [ ] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

The following redirect is currently not skipped: `https://protect.checkpoint.com/v2/___https://discourse.jupyter.org/t/how-to-set-secure-cookie-and-httponly-flag-in-z2jh/25744___.YzJlOmlpYXNhOmM6bzozMGFmMzNiMDdiYjM2ZTJkNDlkZDE2ZjZkOGY0NDYxYjo2OjU2NjA6ZDY4NGY5NDAyNDYzODlhOGVlMjQ2YmQ3NjE3MTU0ODRkZWI0NDE1YTc0ZTRmNTRjZTIzMWNkOTQ0MjVkNWMyNTpoOlQ`

Please support skipping to the URL bracketed in triple underscores.

**Comment by sblask** [comment]
This is a bit too specific for my taste. They could decide to change the format at any time, like use more or less underscores. That is not something I want to Maintain.
