### ISSUE TITLE
Update this extension to support manifest 3 for google chrome new versions

### ISSUE THREAD

**Issue by 123omari123** [sblask-webextensions/webextension-skip-redirect#367]
### New Issue Checklist (tick off like this: `[x]`)

- [x ] I checked existing issues (open and closed) for possible duplicates
- [ ] I can reproduce the problem on the latest stable version (not nightly!)
- [ ] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [ ] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [ ] Firefox
- [x ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x ] Windows

### Description (please include examples/screenshots where applicable)
Hi, Can you update this extension to support manifest 3 for chrome new versions?

**Comment by sblask** [comment]
No, it's not possible, they removed the API that is required. There is no alternative.
