### ISSUE TITLE
Chrome store warning: This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions.

### ISSUE THREAD

**Issue by benatshippabo** [sblask-webextensions/webextension-skip-redirect#368]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [ ] Firefox
- [x] Chrome

### What is your operating system?

- [ ] Linux
- [x] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

Chrome store currently warns users about:

```
This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions.
```

![image](https://github.com/user-attachments/assets/b064c4d4-e35b-4994-a24c-597431ec044a)

This may be related to manifest v3 and the deprecation of `webRequest` apis:

https://github.com/sblask-webextensions/webextension-skip-redirect/blob/e9f0bbb754e4ac38375e6f7d3213a01b6648abf7/background.js#L323-L347

https://github.com/sblask-webextensions/webextension-skip-redirect/blob/e9f0bbb754e4ac38375e6f7d3213a01b6648abf7/background.js#L349-L354

we may need to port over to [`declarativeNetRequest`](https://developer.chrome.com/docs/extensions/reference/api/declarativeNetRequest#before_the_request) instead

**Comment by sblask** [comment]
`declarativeNetRequest` is just not the same thing, so can't be ported to.
